library(shiny)
library(shinythemes)
library(plotly)
library(GSVA)
library(GSEABase)
library(limma)
library(ggplot2)
library(data.table)
library(future)
library(promises)
library(shinyjs)
library(shinybusy)
library(shinydashboard)
plan(multisession)
source("argumentsDataModule.R")
source("modalGSVAModule.R")
source("downloadModule.R")
source("plot1_Module.R")
source("plot2_Module.R")
source("plot3_Module.R")
source("matrixModule.R")
source("geneSetsModule.R")
source("argumentsDataModule.R")
source("closeModule.R")

methodChoices <- c( "GSVA" = "gsva",
                    "ssGSEA" = "ssgsea",
                    "zscore" = "zscore",
                    "PLAGE" = "plage")